### ISSUE TITLE
create a workflow to add/update issues in project board

### ISSUE THREAD

**Issue by JHu-s** [ADACS-Australia/dfisher_2022a#1]

**Comment by gbpoole** [comment]
What do you have in mind here Tiger?  How do you want this to work?

**Comment by JHu-s** [comment]
I'm setting up a project board (https://github.com/ADACS-Australia/dfisher_2022a/projects?type=beta). This is just an issue assigned to myself.

**Comment by gbpoole** [comment]
👍
